# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c873c27d5b9dadb390d5743e2d889988222aa56f68c060c00667b297c4f925eb1b356eab0ab66ce253c366bf24f28d3f9e396d1438dc9794c618c25a4fbd0d2

test:
  secret_key_base: b1ee8457e32058b8f870d483e62e250e698997e5a2bba49b02d6fae3cc00ca7af7fbc37c39d83b42d0a05566afabae71b549ae76955021690aec22da018d07fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
